# Generated by Django 3.2.4 on 2021-06-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='seaLevel',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='swellDirection',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='waveDirection',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='waveHeight',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wavePeriod',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='windWavePeriod',
        ),
    ]
